import { Inter } from "next/font/google";
import "./globals.css";
import MyProvider from "./components/Context/Myprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MyProvider>
      <body className={ inter.className } >{children}</body>
      </MyProvider>
    </html>
  );
}
