name: Java CI with Maven

env:
  NAME: 'Snyk Demo'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      JAVA_VERSION: '21'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
    
    - name: Print environment variables for testing
      run: |
        echo "Testing environment variables:"
        echo "NAME: $NAME"
        echo "JAVA_VERSION: $JAVA_VERSION"
        echo "BUILD: $BUILD"
