name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: production  # References the "production" environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem

          # SSH into EC2 and deploy the application
          ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} << EOF
            # Export environment variables
            export DOMAIN_NAME="${DOMAIN_NAME}"
            export EMAIL_USER="${EMAIL_USER}"
            export EMAIL_PASS="${EMAIL_PASS}"

            # Navigate to your app directory (adjust this if necessary)
            cd ~/app-directory

            # Pull the latest changes from the repository
            git pull origin main

            # Install dependencies
            npm install

            # Build the application (if applicable, for Next.js or similar)
            npm run build

            # Restart the application using PM2 (or whatever process manager you use)
            pm2 restart all || pm2 start npm -- start

            # Optionally, restart the web server if needed (e.g., Nginx or Apache)
            sudo systemctl restart nginx

            # Test the environment variables
            echo "Domain Name: \$DOMAIN_NAME"
            echo "Email User: \$EMAIL_USER"
            echo "Email Pass: \$EMAIL_PASS"
          EOF
