name: ProfileNxT

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: ProfileNxT
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
        ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} '
        
        # Display current directory and home directory contents
        echo "Current directory: $(pwd)"
        echo "Listing home directory:"
        ls -la ~

        # Install Node.js if not already installed
        echo "Installing Node.js..."
        if ! command -v nvm &> /dev/null; then
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
        fi
        nvm install node

        # Install PM2 if not already installed
        echo "Installing PM2..."
        if ! command -v pm2 &> /dev/null; then
          npm install -g pm2
        fi

        # Set up repo URL, branch and directory
        REPO_URL="https://github.com/RatnadeepRoy01/Resume-Maker.git"
        BRANCH="main"
        REPO_DIR="$HOME/ProfileNxT"  # Replace with your actual repo folder name if different

        # Clone or pull the latest changes from the repo
        if [ -d "$REPO_DIR/.git" ]; then
          cd "$REPO_DIR"
          git pull origin "$BRANCH"
        else
          git clone "$REPO_URL" "$REPO_DIR"
          cd "$REPO_DIR"
        fi

        # Navigate to the app directory (adjust if necessary)
        cd "$REPO_DIR"  # Make sure you are in the repo directory
        echo "Current directory after cloning: $(pwd)"

        # If using Next.js, install dependencies
        echo "Installing dependencies..."
        npm install

        # If you have the build step in your app
        echo "Building the app..."
        npm run build

        # Start/restart the application with PM2
        echo "Starting/restarting application..."
        pm2 restart server.js || pm2 start server.js
        '
